# Generated by Django 2.2.2 on 2019-08-19 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='comnents',
        ),
        migrations.AddField(
            model_name='comments',
            name='belong_to_blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_comment', to='blog.Blog'),
        ),
    ]
