# Generated by Django 2.2.2 on 2019-08-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='communication_times',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='follow',
            name='friend_follow_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='follow',
            name='user_follow_friend',
            field=models.BooleanField(default=False),
        ),
    ]
