# Generated by Django 2.2.2 on 2019-08-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190829_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='communication_times',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
