# Generated by Django 2.2.2 on 2019-08-17 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190814_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'get_latest_by': ['-modified_time', '-create_time'], 'ordering': ['-modified_time']},
        ),
    ]
