# Generated by Django 2.2.2 on 2019-08-29 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_auto_20190829_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='post_by',
            field=models.ForeignKey(default='38353b14cfe44c16898b437f94121c7b', on_delete=django.db.models.deletion.CASCADE, related_name='post_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
