# Generated by Django 2.2.2 on 2019-08-30 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_post_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='post_by',
        ),
        migrations.AlterField(
            model_name='blog',
            name='blogger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
