---
apiVersion: v1
kind: PersistentVolume
metadata: 
  name: nfs-5gi-helm
  labels:
    module: helm
    name: nfs-5gi-helm
spec:
  nfs:
    path: /nfs/helm
    server: xx.xx.xxx.33
  accessModes: ["ReadWriteMany"]
  capacity:
    storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: helm 
  namespace: default 
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests: 
      storage: 5Gi

